### PR TITLE
Deprecate Q by Bluebird

### PR DESCRIPTION
**Pull request by Redsandro**
* `Bluebird` is 100 times faster and uses 5% of the memory that `q` uses.
* Removed extraneous promise wrappers
* Arrow functions have no context (AKA faster)

There are some puzzling promise wrappers in the original code. I removed them. I am 91% sure they are unnecessary. But perhaps there is some odd case as to why they are there. At least the tests run fine.

Readability can be improved but I don't want to change anyone's linter settings.

### CODE REVIEW

**Comment by Redsandro** [comment]
I don't understand where the CI error comes from. It's only in node 8. But I'm running node 8 locally, and run the tests locally. :confused:

**Comment by mansona** [comment]
As for the CI changes, they are because your package-lock has merge conflict markers in it. Travis is running `npm ci` which validates the package.json against the package-lock before installing 👍

**Comment by Redsandro** [comment]
> As for the CI changes, they are because your package-lock has merge conflict markers in it.

I have no idea where I dropped that ball. I had it running and testing fine and I pushed the commit. Apologies.

> I am happy to work with you on this PR to remove Q.js but let's not move around any of the other code at the same time

Ok gotcha. Most of the moving was enforced by the linter though due to the arrow syntax.

> I would prefer if we could use native promises instead of bluebird tough.

Native promises without the syntactic sugar from Q or Bluebird require the use of extra wrapper code though; `new promise(function(resolve, reject) {})` everywhere `fcall` or direct `resolve` is used. I'm not sure this change would be as minimal as one might think. I would like your ok on that before I work on another PR.

If code readability is key, would it make sense to forego this effort, create a new major release, drop Node 6 support, and go directly for `async`/`await` in stead of promises? They come with Node 8, and Node 8 is installed by default in Ubuntu 18.04 (which comes with most VPS instances).

**Comment by mansona** [comment]
I'm not really ready to drop Node 6 support yet. This has always been possible to run on all current Node LTS releases and I don't really want to change that yet. There are a few companies with this in production that would not appreciate that move 😞 

I'm ok with extra wrapper code if it removes a dependency 👍 

> Ok gotcha. Most of the moving was enforced by the linter though due to the arrow syntax.

Let's not move things to arrow syntax if we don't need to, just to keep the diff as minimal as possible. The reason I want to keep the diff down on this particular change is that some **behaviour** differences could sneak into the code because of subtle changes in scope etc. and those sorts of subtle changes are unlikely to be covered by tests

**Comment by Redsandro** [comment]
:leftwards_arrow_with_hook: #36

**Pull request closed without merging**
