### PR TITLE
One to many CRITICAL BUG fix

### PR DESCRIPTION
**Pull request by Redsandro**
This will fix broken one-to-many attributes.

@mansona __This is a critical bug fix.__ Please merge ASAP.

### CODE REVIEW

**Comment by mansona** [comment]
@Redsandro do you have a test for this? that fails before the fix is applied?

**Comment by Redsandro** [comment]
No because you rejected my PR for being able to run tests locally.

**Comment by Redsandro** [comment]
Changed existing test to test for the actual type when this differs from attribute name.
This test change was untested. :see_no_evil:
This is cherry-pickable. Just to illustrate. I'm not acquainted enough with the way tests are set up.

**Comment by Redsandro** [comment]
Indeed we observe the error:

* #33
  * `✓ should add array relationships to the object if its on the request body`
* #35
  * `1) should add array relationships to the object if its on the request body` (errored)

**Comment by Redsandro** [comment]
I have protected my branch and started working with it in my application.

`package.json`:
```javascript
{
  "dependencies": {
    "express-autoroute-json": "github:Redsandro/express-autoroute-json#6f0b73ceb0a2372a55e72325fcc7d4eff2cf4051",
  }
}
```

**Comment by mansona** [comment]
express-autoroute-json 3.6.2 published 🎉

**Comment by Redsandro** [comment]
@mansona thanks for the quick publish! :+1:

**Pull request merged**
